# Generated by Django 5.1.1 on 2024-10-03 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('age', models.SmallIntegerField(help_text='Внесите значение возраста в месяцах', verbose_name='Возраст в месяцах')),
                ('breed', models.CharField(max_length=255, verbose_name='Порода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_as_course_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Котенок',
                'verbose_name_plural': 'Котята',
            },
        ),
    ]
