# Generated by Django 5.1.1 on 2024-10-05 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten_show', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='value',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
